config:
  install_tree: /software/$user/spack/install/aws
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  /software/$user/spack/modules/ #to be changed to ?
  build_stage:
    - /software/$user/spack/spack-stages/aws
  install_path_scheme: '{name}/{version}/{compiler.name}/{hash}'
  source_cache: ~/.spack/source_cache
